# Generated by Django 5.2.6 on 2025-09-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('sepatu lari', 'Sepatu Lari'), ('sepatu bola', 'Sepatu Bola'), ('kaos kaki', 'Kaos Kaki'), ('jersey bola', 'Jersey Bola')], default='sepatu lari', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('brand', models.CharField(max_length=255)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
