# Generated by Django 5.2.6 on 2025-09-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sepatu lari', 'Sepatu Lari'), ('sepatu bola', 'Sepatu Bola'), ('kaus kaki', 'Kaus Kaki'), ('jersey bola', 'Jersey Bola')], default='sepatu bola', max_length=20),
        ),
    ]
